before_install:
  - sudo apt-get install -y libfuse-dev
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
language: node_js
node_js:
    - "4"
install:
    - npm i
script:
- npm run test
